### PR TITLE
fix: prevent ReferenceError in strict mode

### LINKED ISSUE #15: `ReferenceError: rstr_sha512 is not defined` in strict mode
https://github.com/mvo5/sha512crypt-node/blob/master/sha512crypt.js#L38-L42

The codes are going to throw in my Angular 13 project, adding the following should fix it.

```js
var rstr_sha512;
var binb_sha512;
var hex_sha512;
var rstr2hex;
var rstr2b64;
```

### PR DESCRIPTION
**Pull request by JounQin**
close #15

### CODE REVIEW

**Comment by JounQin** [comment]
cc @mvo5

**Comment by mvo5** [comment]
This looks very nice! Thank you. Could this "strict" mode be added to the tests as well to ensure that the code does not regress in the future? The current tests are in `.github/workflows/tests.yaml`, would you mind adding (or outlining) the step to check the code with "strict"? Pardon is this is a silly question, I rarely do node anymore these days :)

**Comment by JounQin** [comment]
@mvo5 Maybe we should just add `"use strict"` into `sha512crypt.js`.

**Comment by mvo5** [comment]
Thanks, this looks fine and the tests are happy. One small nitpick - the last commit has a very generic commit message (`Update sha512crypt.js`) - could you please make it a bit more descriptive, e.g. `sha512crypt.js: use strict mode` or something similar?

**Comment by JounQin** [comment]
@mvo5 Anytime to release?

**Comment by mvo5** [comment]
> @mvo5 Anytime to release?

Indeed, let me make one.

**Comment by mvo5** [comment]
> > @mvo5 Anytime to release?
> 
> Indeed, let me make one.

@JounQin I updated it to 1.0.2 and published a new version on npm now.

**Pull request merged**
